### ISSUE TITLE
question: how to deal with circular dependencies with JS?

### ISSUE THREAD

**Issue by Limonische** [typestack/typedi#140] opened 2020-08-19 11:36 UTC
Docs explain how to deal circular dependencies with typescript, but how to do it using js?

**Comment by Limonische** [comment] 2021-01-29 20:43
So i want to reopen this since i still dont get how to make it work.
I try to add my instances to container this way
```
Container.set({ id: 'User.Service', factory: container => new UserService(container) })
Container.set({ id: 'Invoice.Service', factory: container => new InvoiceService(container) })
```

Then in the InvoiceService
```
this.#UserService = container.get('User.Service')
```

And in the UserService
```
this.#InvoiceService = container.get('Invoice.Service')
```

Although i use factories i still get 

findService(identifier) {
               ^
RangeError: Maximum call stack size exceeded

Can anyone pls help me resolve this issue. I've searched in the old and new docs and looked at changelog still no luck.

**Comment by Limonische** [comment] 2021-02-01 13:01
Maybe there are some additional params for get or set, or maybe some other way of getting an instance in the constructor?

**Comment by Limonische** [comment] 2021-02-02 13:47
I've also tried calling Inject manually, but it also doesn't seem to work. Surely there must be some way. Will be waiting for your feedback.

**Comment by NoNameProvided** [comment] 2021-02-13 20:17
Please provide a fully reproducible and __minimal__ code example that causes this error so I can take a look. Thanks.

**Comment by Limonische** [comment] 2021-02-14 00:35
```
// Config
import { Container } from 'typedi'

import InvoiceService from '../services/InvoiceService.js'
import UserService from '../services/UserService.js'

Container.set({ id: 'User.Service', factory: container => new UserService(container) })
Container.set({ id: 'Invoice.Service', factory: container => new InvoiceService(container) })

// User service
export default class UserService {
    #InvoiceService

    constructor(container) {
        this.#InvoiceService = container.get('Invoice.Service')
    }
}

// Invoice service
export default class InvoiceService {
    #UserService

    constructor(container) {
        this.#UserService = container.get('User.Service')
    }
}
```

**Comment by NoNameProvided** [comment] 2021-02-14 12:20
Yeah, that will never work. TypeDI will get the instance only when your factory function is returned it but it will never return it because you are requesting a second class that requests the first. This doesn't work with TS either, for these scenarios, we have property initialization when using decorators. With JS the closest you can get is something like this:

```js
export default class InvoiceService {
    #Container;

    get UserService() {
      this.#Container.get('User.Service')
    }

    constructor(container) {
        this.#Container = container
    }
}
```

This way your class constructor finishes and the instance is created so when you request the other service via the getter TypeDI can return it for you.

**Comment by NoNameProvided** [comment] 2021-02-14 12:31
I will go ahead and close this as answered, if you have any more questions feel free to comment on the issue and I will reopen it for further discussion.

**Closed by NoNameProvided** 2021-02-14 12:31 UTC
Labels: type: question

**Comment by Limonische** [comment] 2021-02-14 13:49
Just tested it and it works really nice, thank you!
