### ISSUE TITLE
@Inject() doesn't work and why should i use Container.get()

### ISSUE THREAD

**Issue by gongul** [typestack/typedi#98] opened 2019-06-21 09:19 UTC
why should i use Container.get()
Am I using typedi wrong way?

t.ts
```
export class T {
	@Inject("userService") private userService!:UserService;

         constructor(){}
}
```

service.ts
```
@Service("userService")
export class UserServiceImpl implements UserService{
}
```

run.ts
```
export default function index(){
 
    const passport =new T();
    // const passport = Container.get(Passport);  why should i use Container.get()
}
```

**Comment by gr3w2** [comment] 2019-06-29 12:47
I have the same issue. Decorator @Inject does not inject dependencies. I tried to call it without params at all, with specifying service name (like in the example above), and with passing function like `@Inject((type) => ClassName)`, but the result is always the same - property is undefined. At the same time `Container.get()` works ok.

**Comment by ninja-** [comment] 2019-07-02 22:02
@gr3w2 yeah it's additional boilerplate that could be avoided in my opinion

**Comment by justinmchase** [comment] 2019-07-24 20:55
You have to create your instances through the container in order for it to do the actual injection and instantiation of dependencies. Simply new'ing your object won't do any of that work.

**Comment by ninja-** [comment] 2019-07-24 21:00
@justinmchase I was wondering can we even use dependency injection when our object isn't a singleton or a service? say we want to inject a Logger into some ORM model class?

**Comment by justinmchase** [comment] 2019-07-24 22:00
Yeah I think it doesn't need to be flagged as a service technically. It will just use the Type as the identifier for a class in the simple case.

```
class Model {
  constructor(private logger: Logger) { }
}

const model = Container.get(Model)
```

**Comment by gongul** [comment] 2019-07-30 01:53
@justinmchase  @ service @ inject You don't automatically create an instance of a container when you use this feature?

**Comment by justinmchase** [comment] 2019-07-30 15:52
Yeah I believe it would get put into the global container if you use the attributes. But yeah if you had a custom container instance and you call `container.get(T)` on a non-@serivce class it will still work just fine.

**Comment by wangjiegulu** [comment] 2020-02-10 11:56
I have the same issue, I think this is a bug, [This solution](https://github.com/typestack/typedi/issues/73#issuecomment-403964309) is only working inject in Controller class. Then I tried follow solution:

Create `typedi.ext.ts`:

```ts
import { Container } from 'typedi';

export function Autowired(name?: string) {
    return function(target: Object, propertyName: string){
        let type = Reflect.getMetadata('design:type', target, propertyName)
        target[propertyName] = Container.get(name || type)
    }
}
```

and then:

```ts
export class T {
	@Autowired("userService") 
         private userService!:UserService;

         constructor(){}
}
```

**Comment by NoNameProvided** [comment] 2020-07-31 00:49
Probably you forgot to import `reflect-metadata`. The below example showcases both constructor injection and property injection.

```ts
import 'reflect-metadata';
import { Container, Service, Inject } from 'typedi';

@Service()
class ExampleClassA {
  test() { console.log('ExampleClassA works'); }
}

@Service()
class ExampleClassB {
  test() { console.log('ExampleClassB works'); }
}

@Service()
class ExampleClass {
  @Inject(type => ExampleClassB)
  private serviceB: ExampleClassB;

  constructor(
    private serviceA: ExampleClassA,
  )  {} 
}

const instance = Container.get(ExampleClass);

instance.serviceA.test();
instance.serviceB.test();
```

Closing as working as intended.

**Closed by NoNameProvided** 2020-07-31 00:49 UTC
Labels: question
