### ISSUE TITLE
Constructor inject not working with custom class decorator

### ISSUE THREAD

**Issue by banny310** [typestack/typedi#111] opened 2019-09-17 15:05 UTC
Hello, I have strange issue when injecting into constructor together custom decorated class.
Please read test case:
```
describe("Constructor inject not working when double decorated", function() {

    beforeEach(() => Container.reset());

    it("should inject service via constructor", function() {
        function logClass() {
            return function _<T extends {new(...args: any[]): {}}>(constructor: T) {
                return class extends constructor {
                    constructor(...args: any[]) {
                        console.log(`Creating: ${constructor.name}`);
                        console.log(args);
                        super(...args);
                        console.log(`Did something after the original constructor!`);
                    }
                };
            };
        }
        @Service()
        class TestService {
        }
        @Service()
        class SecondTestService {
        }
        @Service("mega.service")
        class NamedService {
        }
        @Service()
        @logClass()
        class TestServiceWithParameters {
            constructor(
                public testClass: TestService,
                @Inject(type => SecondTestService) public secondTest: any,
                @Inject("mega.service") public megaService: any
            ) {
            }
        }
        Container.get(TestServiceWithParameters).testClass.should.be.instanceOf(TestService);
        Container.get(TestServiceWithParameters).secondTest.should.be.instanceOf(SecondTestService);
        Container.get(TestServiceWithParameters).megaService.should.be.instanceOf(NamedService);
    });

});
```
Result is:
```
  Constructor inject not working when double decorated
Creating: TestServiceWithParameters
[ TestService {},
  undefined,
  undefined,
  ContainerInstance {
    services: [ [Object], [Object], [Object], [Object] ],
    id: undefined } ]
Did something after the original constructor!
    1) should inject service via constructor
```

But with, commented `@logClass()` decorator everything works fine. Could you help?

**Comment by sh3d2** [comment] 2019-12-31 10:55
Hi, i actually run into the same issue. I think the reason is that decorator overloads the decorated class constructor 

```
return class extends constructor {
                    constructor(...args: any[]) {
```

So when the typedi container gets to registering it, all the constructors' `@Inject` annotations are long gone :( 

I guess one way to make it work is to use property decorators

**Comment by sh3d2** [comment] 2019-12-31 15:03
@banny310 its all about the anonymous class that the decorator returns :( 

```
                return class extends constructor {
...
```

Quick and dirty fix i made (not that im at all proud of it, its hacky as hell) follows:

(changed your test so it works with my chai setup) 


```
import {Service as TypeDiService, Inject, Container} from "typedi";
import {expect} from 'chai';


// here the magic happens - if class is anonymous (any way not to use regex?) travel up the prototype tree
const getBase = (target) => /^class\s+extends/.test(target) ? getBase(Object.getPrototypeOf(target)) : target;

// overridden Service decorator that uses the above hack
const Service = (options?) => (target) => TypeDiService(options)(getBase(target));

describe("Constructor inject not working when double decorated", function() {

    beforeEach(() => Container.reset());

    it("should inject service via constructor", function() {
        function logClass() {
            return function _<T extends {new(...args: any[]): {}}>(constructor: T) {
                return class extends constructor {
                    constructor(...args: any[]) {
                        console.log(`Creating: ${constructor.name}`);
                        console.log(args);
                        super(...args);
                        console.log(`Did something after the original constructor!`);
                    }
                };
            };
        }
        @Service()
        class TestService {
        }
        @Service()
        class SecondTestService {
        }
        @Service("mega.service")
        class NamedService {
        }
        @Service()
        @logClass()
        class TestServiceWithParameters {
            constructor(
                public testClass: TestService,
                @Inject(type => SecondTestService) public secondTest: any,
                @Inject("mega.service") public megaService: any
            ) {
            }
        }
        expect(Container.get(TestServiceWithParameters).testClass).to.be.instanceOf(TestService);
        expect(Container.get(TestServiceWithParameters).secondTest).to.be.instanceOf(SecondTestService);
        expect(Container.get(TestServiceWithParameters).megaService).to.be.instanceOf(NamedService);
    });

});
```

and the result 

```
> NODE_ENV=test istanbul cover mocha -- -t 5000 -u bdd 'test/unit/InjectTest.js' "--grep" "inject not working"



  Constructor inject not working when double decorated
    ✓ should inject service via constructor


  1 passing (14ms)

```

I checked only aginst my common use cases (and it did the job) and also your test case.

**Comment by sh3d2** [comment] 2019-12-31 17:13
Oh, i missed that theres `Container.registerService` method. 

Using it appears more "legit" way to create a custom decorator:
```const Service = (options?) => (target) => Container.registerService({...options, target: getBase(target)});```

**Comment by pbn4** [comment] 2020-02-11 13:34
I just ran into the same issue.  @sh3d2  Why the mentioned PR has been closed and not merged?

**Comment by NoNameProvided** [comment] 2020-07-31 01:29
Closing as out of date. If your issue still persist please open a new issue with a minimal reproduction case.

**Closed by NoNameProvided** 2020-07-31 01:29 UTC
Labels: question
