### ISSUE TITLE
feature: allow @Inject(type => myToken) signature

### ISSUE THREAD

**Issue by Ayzrian** [typestack/typedi#135] opened 2020-07-28 14:52 UTC
The idea is that typescript complains about @Inject(type => SOME_TOKEN), but it is a valid entry and it works.

**Comment by NoNameProvided** [comment] 2020-07-30 22:28
Hi! 

The officially advertised way is to define tokens as value, please use that format when working with tokens.

```ts
import { Token, Service, Inject, Container } from 'typedi';

export const ServiceAToken = new Token<ServiceA>('ServiceA');

@Service(ServiceAToken)
export class ServiceA { }

@Service()
export class ServiceB { 
  @Inject(ServiceAToken)
  private serviceA: ServiceA;
}

const instance = Container.get(ServiceB);
```

Closing this as wontfix. Everything works as intended.

**Closed by NoNameProvided** 2020-07-30 22:28 UTC
Labels: new feature
