### ISSUE TITLE
Parameters on first time initialization

### ISSUE THREAD

**Issue by Granipouss** [typestack/typedi#119] opened 2020-02-05 06:47 UTC
Hi,

Typescript comments on `Container.get` says `Optionally, parameters can be passed in case if instance is initialized in the container for the first time.` but the type does take only one argument (being the service identifier).
Additionally I could not find an example or documentation on it. Is it still possible ? And if so, how ?

Cheers,

**Comment by Hetarnam** [comment] 2020-04-23 15:27
Same problem here.

**Comment by NoNameProvided** [comment] 2020-07-30 23:28
Duplicate of #127.

**Closed by NoNameProvided** 2020-07-30 23:28 UTC
