### ISSUE TITLE
question: circular dependencies with JS

### ISSUE THREAD

**Issue by Limonische** [typestack/typedi#201] opened 2021-01-29 20:46 UTC
So i want to reopen this since i still dont get how to make it work.
I try to add my instances to container this way
```
Container.set({ id: 'User.Service', factory: container => new UserService(container) })
Container.set({ id: 'Invoice.Service', factory: container => new InvoiceService(container) })
```

Then in the constructor of InvoiceService
```
this.#UserService = container.get('User.Service')
```

And in the constructor of UserService
```
this.#InvoiceService = container.get('Invoice.Service')
```

Although i use factories i still get 

findService(identifier) {
               ^
RangeError: Maximum call stack size exceeded

Can anyone pls help me resolve this issue. I've searched in the old and new docs and looked at changelog still no luck.

_Originally posted by @Limonische in https://github.com/typestack/typedi/issues/140#issuecomment-770039367_

**Comment by NoNameProvided** [comment] 2021-01-31 22:47
Duplicate of #140.

**Closed as completed by NoNameProvided** 2021-01-31 22:47 UTC
Labels: status: duplicate, type: question
