### ISSUE TITLE
Exception not thrown on missing binding

### ISSUE THREAD

**Issue by hmil** [typestack/typedi#42] opened 2017-11-13 21:42 UTC
~~Right now the behavior is to inject `undefined` when a service requests an absent binding. This defeats the purpose of a type system as it opens the door for sneaky errors in the middle of a sound method.~~

After doing some research, I found that it's most likely a bug which happens when requiring a service by its type:

Here is what I mean expressed as a test case:
```typescript
it("should throw if the object was not set", () => {
    class Unregistered { }
    // Both assertions should pass but only the first one does:
    expect(() => Container.get("unregistered")).to.throw();
    expect(() => Container.get(Unregistered)).to.throw();
});
```

**Comment by pleerock** [comment] 2017-11-23 09:46
its by design. Service should not be necessary marked with `@Service` decorator. It allows to use third-party constructor-less classes as services. But its a recommendation to mark your services with `@Service` decorator if you want your constructor injections inside this marked service to work  properly.

**Comment by hmil** [comment] 2017-11-23 10:15
I don't quite get your point. My understanding is that under no circumstance should `Container.get` ever return _undefined_. If a service cannot be found, regardless of how it's been requested, typedi should throw.  
Otherwise how can you make sure all dependencies are properly bound when you start your program?

**Comment by pleerock** [comment] 2017-11-23 10:21
Now I do not understand you... Can you provide a good and simple example when current strategy brings issues?

**Comment by hmil** [comment] 2017-11-23 11:06
OK I get it now. I think I was using typedi in a way it was not designed to be used. See below:

```typescript
import {Container, Service, Inject} from "typedi";

export interface Factory {
    create(): void;
}

@Service()
export class CoffeeMaker {
    
    @Inject() // This is an incorrect usage of typedi because Factory is an interface
    private factory: Factory;

    make() {
        this.factory.create();
    }

}

let coffeeMaker = Container.get(CoffeeMaker);
```

The problem is that `typedi` won't complain in this scenario and the member `factory` will not be properly initialized. There should be an error thrown when we call `Container.get(CoffeeMaker)` in this scenario.

(Of course one should use a `Token` for this use case and then typedi works as intended).

**Comment by pleerock** [comment] 2017-11-23 14:35
I've fixed it. Now it will throw an error. This fix will be released in 0.6.0

**Closed** 2017-11-23 14:35 UTC
Labels: question

**Comment by hmil** [comment] 2017-11-23 14:43
Awesome 💯

**Comment by sergeycher** [comment] 2019-04-22 12:29
```
//not marked as a @Service(), i want to instantiate it and add to container manually
class MyLegacyStorage {
    constructor(private someExternalDependency: string) {

    }
}

@Service()
class MyService {
    constructor(public storage: MyLegacyStorage) {
    }
}

@Service()
class MyService2 {
    @Inject()
    public storage: MyLegacyStorage;

    constructor() {
    }
}

@Service()
class MyService3 {
    @Inject('storage')
    public storage: MyLegacyStorage;

    constructor() {
    }
}

//Let's suppose I forgot to manually call `Container.set(MyLegacyStorage, new MyLegacyStorage('my very important token'));` somewhere

it('should throw ServiceNotFoundError #1', () => {
    should.throws(() => {
        console.log(Container.get(MyService).storage);
        //no error
        //prints 'MyLegacyStorage {
        //   someExternalDependency: ContainerInstance { services: [ [Object], [Object] ], id: undefined } }'
    }, ServiceNotFoundError);
});

it('should throw ServiceNotFoundError #2', () => {
    should.throws(() => {
        console.log(Container.get(MyService2).storage);
        //nope
        //prints 'MyLegacyStorage {
        //   someExternalDependency: ContainerInstance { services: [ [Object], [Object] ], id: undefined } }'
    }, ServiceNotFoundError);
});

it('should throw ServiceNotFoundError #3', () => {
    should.throws(() => {
        //yess, finally error
        //prints nothing
        console.log(Container.get(MyService3).storage);
    }, ServiceNotFoundError);
});
```

In all cases I expect an `ServiceNotFoundError`, but I only get it in 3.
Why do the typedi instantiates service even if it was not explicitly marked as a `@Service()`?
