### ISSUE TITLE
@Inject doesn't working with type

### ISSUE THREAD

**Issue by Q00** [typestack/typedi#123] opened 2020-03-11 08:58 UTC
https://github.com/typestack/typedi#services-with-token-name

```typescript
export interface Factory {
    create(): void;
}

export const FactoryService = new Token<Factory>(); 

@Service(FactoryService)
export class BeanFactory implements Factory {
    create() {
    }
}

@Service()
export class CoffeeMaker {
    
    private factory: Factory;

    constructor(@Inject(type => FactoryService) factory: Factory) {
        this.factory = factory;
    }

    make() {
        this.factory.create();
    }

}
```
In this case, parameter of \@Inject is **type => FactoryService**
But I think FactoryService type is Token<Factory>. So FactoryService is not a Function type.

My code is following below.
```typescript

import { User } from '../models/User';
import { Service, Inject, Token } from 'typedi';

export interface UserRepository {
  users(): Promise<User[]>;
}
export const userRepositoryService = new Token<UserRepository>();

@Service()
export class UserService {
  private userRepository: UserRepository;
  constructor(@Inject(userRepositoryService) userRepository: UserRepository) {
    this.userRepository = userRepository;
  }

  async getUsers(): Promise<User[]> {
    const users = await this.userRepository.users();
    return users;
  }
}
```
when I did code same as README, I got an error about Token<any> .
This code helps me resolve error.

Is it wright way to use Inject in README?

**Comment by NoNameProvided** [comment] 2020-07-30 21:29
You cannot use interfaces in injection as it's compiled away (doesn't exists at run-time). You need to use classes. 

Closing as duplicate of #70.

**Closed by NoNameProvided** 2020-07-30 21:29 UTC
